package com.toris.user.model.enums;

public enum RoleType {
    ADMIN,OPERATOR,CONTENTS,MARKETING,EDITOR,EVENT,PRODUCT,USER,PRODUCT_EXTERNAL,BEAUTY,GRAY,EARLY_BIRD,CAFE_STEP,PAROOMIENCER,NB,STATISTICS
}
